-- VehicleConfig: all driveable / flyable vehicles.

local VehicleConfig = {}

VehicleConfig.Vehicles = {
    -- ─── GROUND ──────────────────────────────────────────────────────────────
    Humvee = {
        displayName   = "HMMWV (Humvee)",
        category      = "GroundLight",
        seats         = 5,
        maxSpeed      = 80,
        fuelCapacity  = 100,
        fuelPerStud   = 0.05,
        health        = 500,
        hasTurret     = true,
        turretWeapon  = "M240",
        requireJob    = {},          -- any job can ride, driving may need license
        requireLicense = "DrivingBasic",
        skinnable     = true,
        spawnCost     = 0,
    },
    JLTV = {
        displayName   = "JLTV",
        category      = "GroundLight",
        seats         = 5,
        maxSpeed      = 90,
        fuelCapacity  = 100,
        fuelPerStud   = 0.05,
        health        = 650,
        hasTurret     = true,
        turretWeapon  = "M240",
        requireJob    = { "Army.Infantry", "Army.Ranger", "Army.GreenBeret", "Marines.Rifleman" },
        requireLicense = "DrivingBasic",
        skinnable     = true,
        spawnCost     = 0,
    },
    MRAP = {
        displayName   = "MRAP",
        category      = "GroundArmored",
        seats         = 6,
        maxSpeed      = 60,
        fuelCapacity  = 120,
        fuelPerStud   = 0.08,
        health        = 1200,
        hasTurret     = true,
        turretWeapon  = "M2HB",
        requireJob    = { "Army.Infantry", "Army.Engineer", "Army.MilitaryPolice" },
        requireLicense = "DrivingBasic",
        skinnable     = true,
        spawnCost     = 0,
    },
    LMTV = {
        displayName   = "LMTV Truck",
        category      = "GroundTransport",
        seats         = 12,
        maxSpeed      = 65,
        fuelCapacity  = 150,
        fuelPerStud   = 0.10,
        health        = 700,
        hasTurret     = false,
        requireLicense = "DrivingBasic",
        skinnable     = false,
        spawnCost     = 0,
    },
    Tank = {
        displayName   = "M1A2 Abrams",
        category      = "Armor",
        seats         = 4,
        maxSpeed      = 45,
        fuelCapacity  = 200,
        fuelPerStud   = 0.20,
        health        = 5000,
        hasTurret     = true,
        turretWeapon  = "120mmCannon",
        requireJob    = { "Army.ArmorCrew" },
        requireLicense = "ArmorSchool",
        skinnable     = false,
        spawnCost     = 500,
    },
    Stryker = {
        displayName   = "Stryker ICV",
        category      = "Armor",
        seats         = 9,
        maxSpeed      = 70,
        fuelCapacity  = 150,
        fuelPerStud   = 0.12,
        health        = 2500,
        hasTurret     = true,
        turretWeapon  = "M2HB",
        requireJob    = { "Army.ArmorCrew", "Army.Infantry" },
        requireLicense = "ArmorSchool",
        skinnable     = false,
        spawnCost     = 200,
    },
    Ambulance = {
        displayName   = "Field Ambulance",
        category      = "GroundMedical",
        seats         = 4,
        maxSpeed      = 70,
        fuelCapacity  = 100,
        fuelPerStud   = 0.05,
        health        = 400,
        hasTurret     = false,
        requireJob    = { "Army.Medic", "Navy.Corpsman", "Civilian.Doctor" },
        requireLicense = "DrivingBasic",
        skinnable     = false,
        spawnCost     = 0,
    },
    FireTruck = {
        displayName   = "Fire Truck",
        category      = "GroundEmergency",
        seats         = 4,
        maxSpeed      = 65,
        fuelCapacity  = 120,
        fuelPerStud   = 0.08,
        health        = 600,
        hasTurret     = false,
        requireJob    = { "Civilian.Firefighter" },
        requireLicense = "DrivingBasic",
        skinnable     = false,
        spawnCost     = 0,
    },
    PoliceVehicle = {
        displayName   = "MP Patrol Vehicle",
        category      = "GroundLight",
        seats         = 4,
        maxSpeed      = 90,
        fuelCapacity  = 80,
        fuelPerStud   = 0.04,
        health        = 400,
        hasTurret     = false,
        requireJob    = { "Army.MilitaryPolice", "AirForce.SecurityForces" },
        requireLicense = "DrivingBasic",
        skinnable     = false,
        spawnCost     = 0,
    },
    FuelTruck = {
        displayName   = "Fuel Truck",
        category      = "GroundTransport",
        seats         = 2,
        maxSpeed      = 55,
        fuelCapacity  = 500,
        fuelPerStud   = 0.12,
        health        = 600,
        hasTurret     = false,
        requireJob    = { "Army.Engineer", "Civilian.Mechanic" },
        requireLicense = "DrivingBasic",
        skinnable     = false,
        spawnCost     = 0,
    },

    -- ─── WATERCRAFT ──────────────────────────────────────────────────────────
    Boat = {
        displayName   = "Patrol Boat",
        category      = "Watercraft",
        seats         = 6,
        maxSpeed      = 50,
        fuelCapacity  = 80,
        fuelPerStud   = 0.06,
        health        = 500,
        hasTurret     = true,
        turretWeapon  = "M240",
        requireJob    = { "Navy.Sailor", "Navy.BoatCrew", "Navy.SEAL", "Hostile.Pirate" },
        requireLicense = "BoatSchool",
        skinnable     = false,
        spawnCost     = 0,
    },
    RHIB = {
        displayName   = "RHIB",
        category      = "Watercraft",
        seats         = 8,
        maxSpeed      = 70,
        fuelCapacity  = 60,
        fuelPerStud   = 0.05,
        health        = 300,
        hasTurret     = false,
        requireJob    = { "Navy.Sailor", "Navy.SEAL", "Navy.BoatCrew", "Marines.ForceRecon" },
        requireLicense = "BoatSchool",
        skinnable     = false,
        spawnCost     = 0,
    },

    -- ─── ROTARY WING ─────────────────────────────────────────────────────────
    Helicopter = {
        displayName   = "UH-60 Black Hawk",
        category      = "RotaryWing",
        seats         = 12,
        maxSpeed      = 180,
        fuelCapacity  = 200,
        fuelPerStud   = 0.15,
        health        = 1500,
        hasTurret     = false,
        requireJob    = { "AirForce.Pilot" },
        requireLicense = "RotaryWingLicense",
        canFastRope   = true,
        canHoist      = true,
        skinnable     = false,
        spawnCost     = 0,
    },
    TransportHelicopter = {
        displayName   = "CH-47 Chinook",
        category      = "RotaryWing",
        seats         = 24,
        maxSpeed      = 160,
        fuelCapacity  = 300,
        fuelPerStud   = 0.25,
        health        = 2000,
        hasTurret     = false,
        requireJob    = { "AirForce.Pilot", "AirForce.Loadmaster" },
        requireLicense = "RotaryWingLicense",
        canFastRope   = true,
        skinnable     = false,
        spawnCost     = 0,
    },
    AttackHelicopter = {
        displayName   = "AH-64 Apache",
        category      = "RotaryWing",
        seats         = 2,
        maxSpeed      = 200,
        fuelCapacity  = 150,
        fuelPerStud   = 0.18,
        health        = 1200,
        hasTurret     = true,
        turretWeapon  = "30mmCannon",
        hasRockets    = true,
        requireJob    = { "AirForce.Pilot" },
        requireLicense = "AttackPilotLicense",
        skinnable     = false,
        spawnCost     = 300,
    },

    -- ─── FIXED WING ──────────────────────────────────────────────────────────
    FighterJet = {
        displayName   = "F-15 Strike Eagle",
        category      = "FixedWing",
        seats         = 2,
        maxSpeed      = 600,
        fuelCapacity  = 300,
        fuelPerStud   = 0.30,
        health        = 1000,
        hasTurret     = true,
        turretWeapon  = "M61Cannon",
        hasMissiles   = true,
        requireJob    = { "AirForce.Pilot" },
        requireLicense = "FixedWingLicense",
        skinnable     = false,
        spawnCost     = 500,
    },
    CargoPlane = {
        displayName   = "C-130 Hercules",
        category      = "FixedWing",
        seats         = 64,
        maxSpeed      = 350,
        fuelCapacity  = 500,
        fuelPerStud   = 0.40,
        health        = 3000,
        hasTurret     = false,
        requireJob    = { "AirForce.Pilot", "AirForce.Loadmaster" },
        requireLicense = "FixedWingLicense",
        canAirdrop    = true,
        canParachute  = true,
        skinnable     = false,
        spawnCost     = 0,
    },

    -- ─── UNMANNED ─────────────────────────────────────────────────────────────
    Drone = {
        displayName   = "ISR Drone",
        category      = "Unmanned",
        seats         = 0,
        maxSpeed      = 100,
        fuelCapacity  = 50,
        fuelPerStud   = 0.02,
        health        = 100,
        hasTurret     = false,
        requireJob    = { "AirForce.DronePilot" },
        requireLicense = "DroneLicense",
        skinnable     = false,
        spawnCost     = 0,
    },
}

return VehicleConfig
