-- WeaponConfig: all weapon definitions used by WeaponService and WeaponClient.

local WeaponConfig = {}

-- damage, range (studs), fireRate (rounds/sec), magSize, reloadTime (sec),
-- recoilKick (deg), recoilRecovery (multiplier), automatic, projectileSpeed (studs/s)
WeaponConfig.Weapons = {
    M4A1 = {
        displayName  = "M4A1 Carbine",
        category     = "AssaultRifle",
        damage       = 28,
        headMulti    = 2.0,
        range        = 400,
        fireRate     = 12,
        magSize      = 30,
        maxAmmo      = 150,
        reloadTime   = 2.8,
        recoilKick   = 1.4,
        recoilRecov  = 0.85,
        automatic    = true,
        attachSlots  = { "Optic", "Suppressor", "Grip", "Light", "Laser" },
        skinnable    = true,
    },
    M16 = {
        displayName  = "M16A4",
        category     = "AssaultRifle",
        damage       = 30,
        headMulti    = 2.0,
        range        = 500,
        fireRate     = 3,  -- burst
        magSize      = 30,
        maxAmmo      = 150,
        reloadTime   = 2.6,
        recoilKick   = 1.2,
        recoilRecov  = 0.88,
        automatic    = false,
        attachSlots  = { "Optic", "Grip", "Light" },
        skinnable    = true,
    },
    MK18 = {
        displayName  = "MK18 CQBR",
        category     = "AssaultRifle",
        damage       = 26,
        headMulti    = 2.0,
        range        = 300,
        fireRate     = 13,
        magSize      = 30,
        maxAmmo      = 150,
        reloadTime   = 2.5,
        recoilKick   = 1.5,
        recoilRecov  = 0.83,
        automatic    = true,
        attachSlots  = { "Optic", "Suppressor", "Grip", "Light", "Laser" },
        skinnable    = true,
    },
    M249 = {
        displayName  = "M249 SAW",
        category     = "LMG",
        damage       = 32,
        headMulti    = 1.8,
        range        = 600,
        fireRate     = 14,
        magSize      = 200,
        maxAmmo      = 400,
        reloadTime   = 6.0,
        recoilKick   = 2.2,
        recoilRecov  = 0.7,
        automatic    = true,
        attachSlots  = { "Optic", "Grip" },
        skinnable    = false,
    },
    M240 = {
        displayName  = "M240B",
        category     = "LMG",
        damage       = 38,
        headMulti    = 1.8,
        range        = 700,
        fireRate     = 11,
        magSize      = 100,
        maxAmmo      = 300,
        reloadTime   = 7.0,
        recoilKick   = 3.0,
        recoilRecov  = 0.65,
        automatic    = true,
        attachSlots  = { "Optic" },
        skinnable    = false,
    },
    M110 = {
        displayName  = "M110 SASS",
        category     = "SniperRifle",
        damage       = 85,
        headMulti    = 2.5,
        range        = 1200,
        fireRate     = 1.2,
        magSize      = 10,
        maxAmmo      = 40,
        reloadTime   = 3.5,
        recoilKick   = 4.0,
        recoilRecov  = 0.6,
        automatic    = false,
        attachSlots  = { "Optic", "Suppressor", "Bipod" },
        skinnable    = true,
    },
    M17 = {
        displayName  = "M17 Pistol",
        category     = "Pistol",
        damage       = 20,
        headMulti    = 2.0,
        range        = 100,
        fireRate     = 6,
        magSize      = 17,
        maxAmmo      = 68,
        reloadTime   = 2.0,
        recoilKick   = 1.8,
        recoilRecov  = 0.9,
        automatic    = false,
        attachSlots  = { "Suppressor", "Light", "Laser" },
        skinnable    = true,
    },
    Shotgun = {
        displayName  = "M590 Shotgun",
        category     = "Shotgun",
        damage       = 18,  -- per pellet, 8 pellets
        headMulti    = 1.5,
        pellets      = 8,
        range        = 60,
        fireRate     = 1.5,
        magSize      = 8,
        maxAmmo      = 32,
        reloadTime   = 4.0,
        recoilKick   = 5.0,
        recoilRecov  = 0.6,
        automatic    = false,
        attachSlots  = { "Light" },
        skinnable    = false,
    },
    SniperRifle = {
        displayName  = "M2010 ESR",
        category     = "SniperRifle",
        damage       = 120,
        headMulti    = 3.0,
        range        = 1800,
        fireRate     = 0.6,
        magSize      = 5,
        maxAmmo      = 25,
        reloadTime   = 4.0,
        recoilKick   = 6.0,
        recoilRecov  = 0.5,
        automatic    = false,
        attachSlots  = { "Optic", "Suppressor", "Bipod" },
        skinnable    = true,
    },
    SmokePrimary = {
        displayName  = "Smoke Grenade",
        category     = "Thrown",
        damage       = 0,
        fuseTime     = 1.5,
        smokeDuration = 12,
        range        = 40,
        skinnable    = false,
    },
    Flashbang = {
        displayName  = "Flashbang",
        category     = "Thrown",
        damage       = 0,
        stunDuration = 3.5,
        fuseTime     = 1.5,
        range        = 35,
        skinnable    = false,
    },
    FragGrenade = {
        displayName  = "Frag Grenade",
        category     = "Thrown",
        damage       = 150,
        blastRadius  = 12,
        fuseTime     = 2.5,
        range        = 40,
        skinnable    = false,
    },
}

-- Optic definitions (referenced by attachSlots)
WeaponConfig.Optics = {
    IronSights  = { displayName = "Iron Sights",      zoom = 1.0 },
    RedDot      = { displayName = "Red Dot Sight",     zoom = 1.5 },
    Holographic = { displayName = "Holographic",       zoom = 1.5 },
    ACOG        = { displayName = "ACOG 4x",           zoom = 4.0 },
    LPVO        = { displayName = "1-6x LPVO",         zoom = 6.0 },
    NightScope  = { displayName = "Night Vision Scope", zoom = 4.0, nightVision = true },
    SnipScope   = { displayName = "10x Sniper Scope",  zoom = 10.0 },
}

WeaponConfig.Suppressors = {
    LightSuppressor = { displayName = "Suppressor",      noiseReduction = 0.7 },
}

-- Weapon mastery XP thresholds (kills with weapon)
WeaponConfig.MasteryTiers = { 0, 50, 150, 300, 500, 750, 1000 }
WeaponConfig.MasteryRewards = {
    [2] = "WeaponSticker_Bronze",
    [4] = "WeaponSkin_Camo",
    [6] = "WeaponSkin_Gold",
    [7] = "WeaponSkin_Diamond",
}

return WeaponConfig
